### PR TITLE
update chess game layout

### PR DESCRIPTION
**Pull request by Prabhakar-Poudel**

### CODE REVIEW

**Review by codemayank — COMMENTED** [review]
Can you please provide a screenshot of the updated layout.

**Comment by Prabhakar-Poudel** [comment]
Phone

layout Mobile



PC

layoutPC

**Comment by Prabhakar-Poudel** [comment]
@codemayank 
>  Can you please provide a screenshot of the updated layout.

Done.

**Comment by codemayank** [comment]
I would suggest a few changes that would make the UI look better.
1. Show the player rating below their name.
2. Reduce the font size of player rating.
3. In desktop view, the player information and time should be in line with the chess board.
4. Show the name and time for both players on the same side.

You may refer to this design.

Game Play Ongoing

**Comment by Prabhakar-Poudel** [comment]
PC
pclayout


Mobile
moblayout


@codemayank Updated design as requested.

**Review by codemayank — APPROVED** [review]

**Pull request merged**
